# RT - Secret

# Stripeのキーです。使わないのなら未入力にしてください。
[stripe]
api_key = ""
endpoint_secret = ""

[oauth]
# OAuthの情報です。使わないのなら未入力で良いです。
client_id = ""
client_secret = ""

[mysql]
# MySQLへの接続情報です。
# aiomysqlというライブラリの`create_pool`という関数にキーワード引数として以下が渡されます。
host = "localhost"
user = "rt-bot"
password = "..."
db = "rtdb"
autocommit = true
